import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "./menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* A fixed-height, sticky menu */}
        <header className="sticky top-0 z-50 h-16">
          <Menu />
        </header>

        {/* Push everything down by 4rem (h-16) */}
        <main className="pt-4">
          {children}
        </main>
      </body>
    </html>
  );
}
